services:
  api:
    build: ./backend
    container_name: go-backend
    volumes:
      - ./backend:/go-backend
    ports:
      - "8080:8080"
    tty: true
  postgres:
    build:
      context: ./db
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./db/ddls:/ddls
      - ./db/dmls:/dmls
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/react-frontend
      - node_modules:/react-frontend/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_data:
  node_modules:
