services:
  api:
    build: ./backend
    container_name: go-backend
    volumes:
      - ./backend:/go-backend
    ports:
      - "8080:8080"
    tty: true
  postgres:
    build:
      context: ./db
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./db/ddls:/ddls
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
